# ??? ?? ?????? ??
spring.application.name=vendingmachine

# ? ?? ?? ??
server.port=8080

# ==========================================
# ? MariaDB ?????? ?? ??
# ==========================================
spring.datasource.url=jdbc:mariadb://localhost:3306/vending_machine?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql1234

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ==========================================
# ?? JPA (?????? ?? ??) ??
# ==========================================
# ?? ??? ?? DB ???? ???? ???? ??
spring.jpa.hibernate.ddl-auto=update
# ???? DB? ??? SQL(???)? ??? ?? ???
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true